import {Montserrat} from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Toaster } from "sonner";

const ubuntu = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "MediCal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.className} antialiased`}
      >
        <div className="md: px-20">
        <Header/>
        {children}
        <Toaster/>
        </div>
        <Footer/>
      </body>
    </html>
  );
}
